routes/web.php
<?php

use App\Http\Controllers\FollowerController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\TwitController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();
Route::middleware('auth')->group(function () {
    Route::controller(TwitController::class)->name('twit.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/', 'store')->name('store');
        Route::get('/{twit}/edit', 'edit')->name('edit');
        Route::patch('/{twit}', 'update')->name('update');
        Route::delete('/{twit}', 'destroy')->name('delete');
    });
    Route::prefix('user')->controller(UserController::class)->name('user.')->group(function () {
        Route::get('/{user}', 'show')->name('index');
        Route::get('/{user}/edit', 'edit')->name('edit');
        Route::patch('/{user}', 'update')->name('update');
    });
    Route::post('/like', [LikeController::class, 'like'])->name('like');
    Route::post('/follow', [FollowerController::class, 'follow'])->name('follow');

});

app/Models/Twit.php
<?php

namespace App\Models;

use App\Models\Trait\HasLike;
use App\Models\Trait\Likeable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Twit extends Model
{
    use HasFactory,Likeable;

    protected $table = 'twits';
    protected $guarded = false;
    use softDeletes;

    public $timestamps = true;

    public function author(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function hasUserLike($user_id)
    {
        $x = Like::where('user_id', '=', $user_id)->where('twit_id', '=', $this->id)->get();
        if ($x) {
            foreach ($x as $value) {
                if ($value->user_id === $user_id) {
                    return true;
                }
            }
        }
        return false;
    }

    public function like()
    {
        $x = Like::where('user_id', '=', Auth::id())->where('twit_id', '=', $this->id)->count();
        if ($x != 0) {
            $x = Like::where('user_id', '=', Auth::id())->where('twit_id', '=', $this->id)->get();
            foreach ($x as $value) {
                return 1;
            }
        }
        return 0;
    }
}

app/Http/Controllers/TwitController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\EditTwitRequest;
use App\Http\Requests\NewTwitRequest;
use App\Models\Twit;
use App\Services\twitService;


class TwitController extends Controller
{
    public function __construct(twitService $twitService)
    {
        $this->twitService=$twitService;
    }
    public function index(){
        $twits=$this->twitService->getAll();
        return view('twit.index',)->with('twits',$twits);
    }
    public function create(){
        return view('twit.create');
    }
    public function store(NewTwitRequest $request,Twit $twit){
        $this->twitService->store($request);
        return redirect()->route('twit.store');
    }
    public function edit(EditTwitRequest $request,Twit $twit){

        return view('twit.edit')->with('twit',$twit);
    }
    public function update(EditTwitRequest $request,Twit $twit){
        $this->twitService->update($request,$twit);
        return redirect()->route('twit.index');
    }
    public function destroy(Twit $twit){
        $twit->delete();
        return redirect()->route('twit.index');
    }
}

resources/views/twit/create.blade.php
@extends('layouts.app')

@section('content')
    <form action="{{route('twit.store')}}" method="post" style="width: 40%;
  margin: 0 auto;">
        <div>
            <a href="{{route('twit.index')}}" style="text-decoration: none;">
                <button type="button" class="btn btn-outline-secondary"><- Back</button>
            </a>
        </div>
        @csrf
        <div class="mb-3">
            <label for="text" class="form-label">Text</label>
            <textarea class="form-control" name="text" id="text" rows="6" style="height:100%;width: 80%;"
                      placeholder="Content">{{old('text')}}</textarea>
            @error('text')
            <p class="text-danger">{{$message}}</p>
            @enderror
        </div>
        <div class="mb-3">
            <div class="form-check">
                <input class="form-check-input" type="checkbox"  name="only_for_followers" value="1" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    Only for followers
                </label>
            </div>
        </div>
        <div class="mb-3">
            <label for="party" class="mb-3">Schedule posting the twit:</label><br>
            <input id="party" type="datetime-local" name="partydate" value="">
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
@endsection

resources/views/twit/edit.blade.php
@extends('layouts.app')

@section('content')
    <div>
        <a href="{{route('twit.index')}}" style="text-decoration: none;">
            <button type="button" class="btn btn-outline-secondary"><- Back</button>
        </a>
    </div>

    <form action="{{route('twit.update',$twit->id)}}" method="post" style="width: 40%;
  margin: 0 auto;">
        @csrf
        @method('patch')

        <div class="mb-3">
            <label for="text" class="form-label">Text</label>
            <textarea class="form-control" name="text" id="text" rows="6" style="height:100%;width: 80%;"
                      placeholder="Content">{{old('text', isset($twit->text) ? $twit->text : '')}}</textarea>
            @error('text')
            <p class="text-danger">{{$message}}</p>
            @enderror
        </div>
        <div class="mb-3">
            <div class="form-check">
                <input class="form-check-input" type="checkbox"  name="only_for_followers" value="{{old('only_for_followers', isset($twit->only_for_followers) ? $twit->only_for_followers : 1) }}" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    Only for followers
                </label>
            </div>
        </div>
        <div class="mb-3">
            <label for="party" class="mb-3">Schedule posting the twit:</label><br>
            <input id="party" type="datetime-local" name="partydate" value="">
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
@endsection

resources/views/twit/index.blade.php
@extends('layouts.app')

@section('content')
    @foreach($twits as $twit)
        @can('view', $twit)
            <div class="card"
             style="display: block;  width: 30%;  margin: 1% auto;text-align: center;vertical-align: middle;">
            <div class="card-body">
                <x-delete-edit-buttons :twit=$twit />
                <div class="grid-containert" style="display: inline-flex;">
                    <div class="grid-itemt " style="vertical-align: middle;">
                        <a href="{{route('user.index',$twit->author->id)}}}" style="text-decoration: none;">
                            <h7 class="card-title"
                                style="text-align: left;">{{$twit->author->first_name}} {{$twit->author->last_name}}</h7>
                        </a>
                    </div>
                    <div class="grid-itemt m-xl-2" style="vertical-align: middle;">
                        <h6 class="card-subtitle mb-2 text-muted">    {{$twit->created_at}}</h6>
                    </div>
                </div>
            </div>
                <div><h6 class="card-subtitle mb-2 text-muted">{{$twit->text}}</h6></div>
            <x-like :twit=$twit />
        </div>
        @endcan
    @endforeach()
@endsection
@section('script')
    <script src="{{asset('js/like.js')}}"></script>
@endsection