routes/web.php
<?php

use App\Http\Controllers\FollowerController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\TwitController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();
Route::middleware('auth')->group(function () {
    Route::controller(TwitController::class)->name('twit.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/', 'store')->name('store');
        Route::get('/{twit}/edit', 'edit')->name('edit');
        Route::patch('/{twit}', 'update')->name('update');
        Route::delete('/{twit}', 'destroy')->name('delete');
    });
    Route::prefix('user')->controller(UserController::class)->name('user.')->group(function () {
        Route::get('/{user}', 'show')->name('index');
        Route::get('/{user}/edit', 'edit')->name('edit');
        Route::patch('/{user}', 'update')->name('update');
    });
    Route::post('/like', [LikeController::class, 'like'])->name('like');
    Route::post('/follow', [FollowerController::class, 'follow'])->name('follow');

});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use App\Models\Trait\Followable;
use App\Models\Trait\HasLike;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable,Followable,HasLike;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $table = 'users';
    protected $guarded = false;
    use softDeletes;


    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function twits()
    {
        return $this->hasMany(Twit::class, 'user_id', 'id');
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserUpdateRequest;
use App\Models\User;
use App\Services\userService;


class UserController extends Controller
{
    public function __construct(userService $userService)
    {
        $this->userService=$userService;
    }

    public function show(User $user)
    {
        return view('user.index', compact('user'));
    }

    public function edit(User $user, UserUpdateRequest $request)
    {
        return view('user.edit', compact('user'));
    }

    public function update(User $user, UserUpdateRequest $request)
    {
        $this->userService->update($request);
        return redirect()->route('user.index', $user->id);
    }

}

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="m-4">
        <a href="{{route('user.index',Auth::id())}}" style="text-decoration: none;">
            <button type="button" class="btn btn-outline-dark">Back to twits</button>
        </a>
    </div>
    <form action="{{route('user.update',$user->id)}}" method="post" enctype="multipart/form-data">
        @csrf
        @method('patch')
        <div class="row mb-3">
            <label for="first_name" class="col-md-4 col-form-label text-md-end">{{ __('First name') }}</label>
            <div class="col-md-6">
                <input id="first_name" type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{ old('first_name', isset($user->first_name) ? $user->first_name : '') }}"  autocomplete="first_name" autofocus>
            </div>
        </div>
        <div class="row mb-3">
            <label for="last_name" class="col-md-4 col-form-label text-md-end">{{ __('Last name') }}</label>
            <div class="col-md-6">
                <input id="last_name" type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{ old('last_name', isset($user->last_name) ? $user->last_name : '') }}"  autocomplete="last_name" autofocus>
            </div>
        </div>
        <div class="row mb-3">
            <label for="email" class="col-md-4 col-form-label text-md-end">{{ __('Email Address') }}</label>
            <div class="col-md-6">
                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email', isset($user->email) ? $user->email : '') }}"  autocomplete="email">
            </div>
        </div>
        <div class="card" style="display: block;  width: 30%;  margin: 1% auto;text-align: center;vertical-align: middle;">
            <label class="form-label" for="customFile">Avatar image</label>
            <input type="file" class="form-control" id="customFile" name="avatar"/>
            <button type="submit" class="btn btn-primary">confirm</button>
        </div>
    </form>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="m-4">
        <a href="{{route('twit.index')}}" style="text-decoration: none;">
            <button type="button" class="btn btn-outline-dark">Back to twits</button>
        </a>
    </div>
    @include('user.includes.info')
    <hr>
    <div class="grid-container">
        <div class="grid-item">
            @include('user.includes.followers')
        </div>
        <div class="grid-item">
            @include('user.includes.user_twits')
        </div>
        <div class="grid-item">
            @include('user.includes.followings')
        </div>
    </div>
@endsection
@section('script')
    <script src="{{asset('js/follow.js')}}"></script>
@endsection