routes/web.php
<?php

use App\Http\Controllers\FollowerController;
use App\Http\Controllers\LikeController;
use App\Http\Controllers\TwitController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();
Route::middleware('auth')->group(function () {
    Route::controller(TwitController::class)->name('twit.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/', 'store')->name('store');
        Route::get('/{twit}/edit', 'edit')->name('edit');
        Route::patch('/{twit}', 'update')->name('update');
        Route::delete('/{twit}', 'destroy')->name('delete');
    });
    Route::prefix('user')->controller(UserController::class)->name('user.')->group(function () {
        Route::get('/{user}', 'show')->name('index');
        Route::get('/{user}/edit', 'edit')->name('edit');
        Route::patch('/{user}', 'update')->name('update');
    });
    Route::post('/like', [LikeController::class, 'like'])->name('like');
    Route::post('/follow', [FollowerController::class, 'follow'])->name('follow');

});

resources/views/includes/authentication.blade.php
@guest
    @if (Route::has('login'))
        <li class="nav-item">
            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
        </li>
    @endif
    @if (Route::has('register'))
        <li class="nav-item">
            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
        </li>
    @endif
@else
    <li class="nav-item dropdown">
        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false" v-pre>
            {{ Auth::user()->email }}
        </a>
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ route('logout') }}"
               onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                {{ __('Logout') }}
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>
        </div>
    </li>
@endguest

resources/views/includes/header.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container" >
        <a href="{{route('twit.index')}}" style="text-decoration: none ;alignment: left;"><h3>TwitUA</h3></a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ms-auto">
                @if(Auth::check())
                    <div class="">
                        <a href="{{route('twit.create')}}" style="text-decoration: none;">
                            <button type="button" class="btn btn-outline-dark">Create post</button>
                        </a>
                    </div>
                    <div class="m-xl-3">
                        <a href="{{route('user.index',Auth::user()->id)}}}" style="text-decoration: none;">
                            {{ Auth::user()->first_name}} {{ Auth::user()->last_name}}
                        </a>
                    </div>
                    @if(Auth::user()->avatar_url_thumb)
                        <div class="">
                            <a href="{{route('user.index',Auth::id())}}}" style="text-decoration: none;">
                                <img src="{{Auth::user()->avatar_url_thumb}}" class="rounded-circle"
                                     style="width: 50px;"
                                     alt="" >
                            </a>
                        </div>
                    @endif
                @endif
                <!-- Authentication Links -->
                @include('includes.authentication')
            </ul>
        </div>
    </div>
</nav>